### ISSUE TITLE
i get this error :    'convertFromHTML' is not defined  no-undef

### ISSUE THREAD

**Issue by jpca999** [facebook/draft-js#1552] opened 2017-12-06 01:28 UTC
![image](https://user-images.githubusercontent.com/1026325/33639741-9f39212a-d9e1-11e7-8881-ea7fa74c08e6.png)

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

**Comment by juliankrispel** [comment] 2017-12-12 06:48
Hey @jpca999 thanks for reaching out.

This looks like an error occurred in your repository, without instructions to reproduce this we can't really help. Hence I'm closing this issue. 

Btw - please join the draft js community on slack for more immediate help: https://draftjs.herokuapp.com

**Closed by juliankrispel** 2017-12-12 06:48 UTC
