### ISSUE TITLE
Cutting text in code-block(overflow: auto) causes a window scroll

### ISSUE THREAD

**Issue by ambar** [facebook/draft-js#1528] opened 2017-11-23 06:44 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
scrolled to window top

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
https://jsfiddle.net/0n1okd4c/1/

```
.public-DraftStyleDefault-pre {
  overflow: auto;
}
```

**What is the expected behavior?**
dot not scroll

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
`0.10.3`

<img width="1136" alt="editoncut" src="https://user-images.githubusercontent.com/105919/33161189-bf9b3a22-d05c-11e7-8fe0-deb6b0456df4.png">

**Comment by robbertbrak** [comment] 2017-11-23 08:13
Same as #1427, I think.

**Comment by juliankrispel** [comment] 2017-12-12 10:08
duplicate of #1427

**Closed by juliankrispel** 2017-12-12 10:08 UTC
