### ISSUE TITLE
Some emoji cannot delete once

### ISSUE THREAD

**Issue by springhack** [facebook/draft-js#1167] opened 2017-04-23 08:51 UTC
Try this emoji: ♥️ , and delete it, you will saw a black heart.
Unicode is: `\u2764\ufe0f`

Can pick this emoji form macOS's input method.

**Comment by mmmoussa** [comment] 2017-04-25 16:48
This is a duplicate of #1105

**Closed by mmmoussa** 2017-04-25 16:48 UTC
