### ISSUE TITLE
Strange behavior when i keep pressing the return key in the Editor

### ISSUE THREAD

**Issue by jackmatrix** [facebook/draft-js#1096] opened 2017-03-26 06:31 UTC
Just test by yourself  to keep pressing enter (return) key inside the [draft js editor](https://draftjs.org/) for a long time .

In my case, my browser start ro freeze and the editor lagging.

What is the causes ?How can i fix it ?

Thanks for suggestions.

**Comment by jatins** [comment] 2017-03-28 13:00
Tried that. Didn't notice anything strange. 
I am using Chrome.

**Comment by flarnie** [comment] 2017-06-15 23:47
@jackmatrix Does this still reproduce for you? What browser were you using? If you open the console, are there any errors?

**Comment by flarnie** [comment] 2017-06-26 15:59
Looks like this may be fixed in the latest version of Draft. Please open a new issue if this is still happening for you, and give us more details about how to reproduce the issue.

**Closed by flarnie** 2017-06-26 15:59 UTC
Labels: needs-more-info
