### ISSUE TITLE
have some function to use react 0.14.x?

### ISSUE THREAD

**Issue by Linbubin** [facebook/draft-js#1556] opened 2017-12-11 06:18 UTC
For some reasons, I used the react `0.14.x` version, so if you want to ask, is there any way to make it available in the `0.14.x` version?

if i use the draft-js lastest version , have Warning
```
Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional.
```

**Comment by juliankrispel** [comment] 2017-12-12 05:55
duplicate of #81

@Linbubin to silence this warning you need to upgrade to 0.15

Also btw - please join the draft js community on slack for more immediate help: https://draftjs.herokuapp.com

**Closed by juliankrispel** 2017-12-12 05:55 UTC
