### ISSUE TITLE
Jump when continue writing in IE

### ISSUE THREAD

**Issue by Nikcrysis** [facebook/draft-js#1184] opened 2017-04-28 13:46 UTC
Draft-js 0.10.0
Internet Explorer 11

<img src="https://i.gyazo.com/af2170e461502498788b5c0d3ec7f9dc.gif">

**Comment by flarnie** [comment] 2017-07-07 18:49
Thanks for the gif and for reporting this! It's a bit hard for me to tell exactly how to reproduce this - I just tried in IE11 by doing the following:

1) Enter 10-20 lines of gibberish
2) click to move the cursor to a line in the middle
3) enter 5 more lines
4) use the down arrow to move the focus down one line.

Can you give more details about how to reproduce this? Does it happen every time? What version of Draft are you using?

Thanks. 🌼

**Comment by flarnie** [comment] 2017-08-11 20:39
Hi again - just closing this since it has not been active, but please reopen if it's still an issue for you and let us know how to reproduce it.

**Closed by flarnie** 2017-08-11 20:39 UTC
Labels: needs-more-info
