### ISSUE TITLE
If a lot of spaces are typed at the end of the line, it doesn't break to the next line

### ISSUE THREAD

**Issue by rahul1995** [facebook/draft-js#2255] opened 2019-11-20 14:53 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently, if user types a lot of spaces in the end of a line, the line doesn't break to the next line

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/gmertk/e61z7nfa/.**
![chrome-capture](https://user-images.githubusercontent.com/7647789/69248434-4cef2480-0bd2-11ea-9737-45581f94a3e4.gif)

**What is the expected behavior?**
If spaces are more than a line can contain, they should break (wrap) to the next line.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
DraftJS version 0.11.0 on Windows

Note: I tried and I think all spaces should be replaced by nbsp but getText() methods should give strings with normal spaces. However, I doubt if this solution is elegant.

**Comment by mrkev** [comment] 2019-11-20 18:57
Duplicate of https://github.com/facebook/draft-js/issues/2119

**Closed by mrkev** 2019-11-20 18:57 UTC
