### ISSUE TITLE
AtomicBlockUtils.insertAtomicBlock creates 3 blocks(2 ` unstyled, 1 ` atomic) instead of one atomic

### ISSUE THREAD

**Issue by norayr93** [facebook/draft-js#1985] opened 2019-01-28 15:27 UTC
```
addCTABox = (boxTitle, boxText, buttonText, url, ctaTargetLinkOption) => {
    const { editorState, onChange } = this.props;
    const { currentEntity } = this.state;
    let selection = editorState.getSelection();

    if (currentEntity) {
      // console.log(editorState, 'editorState');
      const entityRange = getEntityRange(editorState, currentEntity);
      // console.log(entityRange, 'entityRangeeeee');
      selection = selection.merge({
        anchorOffset: entityRange.start,
        focusOffset: entityRange.end,
      });
    }
    const contentState = editorState.getCurrentContent();

    const contentStateWithEntity = contentState.createEntity(
      'CTA_BOX',
      'MUTABLE',
      {
        ctaTitle: boxTitle,
        ctaText: boxText,
        ctaButtonText: buttonText,
        url,
        targetOption: ctaTargetLinkOption,
      },
    );
    let newEditorState;
    const entityKey = contentStateWithEntity.getLastCreatedEntityKey();

    if (currentEntity) {
      newEditorState = EditorState.push(
        editorState,
        contentStateWithEntity,
        'insert-characters',
      );
    } else {
      // let's assume that currentEntity is null and it sets the new state
      newEditorState = EditorState.set(
        editorState,
        { currentContent: contentStateWithEntity },
        'insert-characters',
      );
    }

    newEditorState = AtomicBlockUtils.insertAtomicBlock(
      newEditorState,
      entityKey,
      `${buttonText}`,
    );

    onChange(newEditorState);
    this.doCollapse();
  };
```
![screenshot from 2019-01-28 19-23-44](https://user-images.githubusercontent.com/36794263/51846120-674dce00-2332-11e9-87bb-1fcf66b31880.png)

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
0.10.5

Why does it create 3 blocks instead of one atomic ?

**Comment by jianfenkezhan** [comment] 2019-01-29 09:50
yes, it happens to me. how to fix?

**Comment by thibaudcolas** [comment] 2019-01-29 22:20
This is done on purpose, see https://github.com/facebook/draft-js/issues/327#issuecomment-212514270.

**Comment by niveditc** [comment] 2019-02-02 07:15
Closing since this is expected behavior (thanks for digging up the relevant issue @thibaudcolas 👍 )

**Closed by niveditc** 2019-02-02 07:15 UTC

**Comment by norayr93** [comment] 2019-02-02 09:32
@niveditc Msy be it is the expected behaivour , but **getSelectedBlocksType(editorState)**  from **draftjs-utils** returns always the _unstyled_ one. How in that case if it is expected behaviour , get that block ?
