### ISSUE TITLE
Placeholder showing for lists

### ISSUE THREAD

**Issue by oscarmorrison** [facebook/draft-js#1205] opened 2017-05-11 22:00 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Placeholder is showing for lists (ordered and unordered)
![image](https://cloud.githubusercontent.com/assets/1651212/25973807/b1345a64-3673-11e7-89f1-9d4fc7d345ee.png)

**What is the expected behavior?**
Placeholder should not show

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

"draft-js": "^0.10.0"

**Comment by pcsms** [comment] 2018-01-16 16:11
Someone got around to this situation?

**Comment by thibaudcolas** [comment] 2018-01-16 16:47
This is the same problem as what the [docs](https://draftjs.org/docs/api-reference-editor.html#placeholder) mention:

> For instance, in the rich editor example, the placeholder is hidden when the user changes block styling in an empty editor. This is because the placeholder may not line up with the cursor when the style is changed.

For my editor, I've made a `shouldHidePlaceholder` function: https://github.com/springload/draftail/blob/4ff6be3b8134881deaf51cda02f076183be7f358/lib/api/DraftUtils.js#L234-L243 which I then use to toggle the following [`Editor--hide-placeholder` CSS class](https://github.com/springload/draftail/blob/3a493622a7838bc4cf9accbe17edbc06dce27dd6/lib/components/DraftailEditor.scss#L6):

```scss
.Editor--hide-placeholder .public-DraftEditorPlaceholder-root {
  display: none;
}

**Comment by niveditc** [comment] 2019-01-19 23:18
Closing the issue since this is expected behavior.

**Closed by niveditc** 2019-01-19 23:18 UTC
