### ISSUE TITLE
 How to detect unicode input event?

### ISSUE THREAD

**Issue by bowbowbow** [facebook/draft-js#693] opened 2016-09-29 12:46 UTC
handleBeforeInput handler(https://facebook.github.io/draft-js/docs/api-reference-editor.html#handlebeforeinput) is not called when unicode like Korean is inserted.

**Comment by davidchang** [comment] 2016-10-14 00:32
Thanks for opening the bug, @bowbowbow - I'm going to close this as a duplicate of https://github.com/facebook/draft-js/issues/311

**Closed by davidchang** 2016-10-14 00:32 UTC
