### ISSUE TITLE
After pasting text from outside of the editor, undo (cmd + z) does not clear the pasted text to the previous text.

### ISSUE THREAD

**Issue by vnovick** [facebook/draft-js#754] opened 2016-10-30 14:37 UTC
After pasting text, undo won't clear the text. I expect the text to get cleared to the previous state.
Happens in all browsers for "draft-js": "^0.8.1", version. It didn't work also in previous versions of Draft.js.

**Comment by thibaudcolas** [comment] 2018-01-16 14:02
I can't reproduce this in my test editor (https://jsfiddle.net/thibaudcolas/Lo2zL37h/), in any browser.

GIF:

![undo-paste-draftjs](https://user-images.githubusercontent.com/877585/34992708-add6fda4-fad6-11e7-9a81-2fea743c3249.gif)

**Comment by niveditc** [comment] 2018-09-09 05:15
Closing due to no repro.

**Closed by niveditc** 2018-09-09 05:15 UTC
