### ISSUE TITLE
OnFocus and OnBlur Issue

### ISSUE THREAD

**Issue by archieherbias** [facebook/draft-js#1284] opened 2017-07-12 09:19 UTC
**Do you want to request a *feature* or report a *bug*?**
No

**What is the current behavior?**
`onBlur` event is not fired when not updating the text value. Although I called `onFocus` after double clicking some `div`. `onBlur` is fired when I have changed the value of the text but if I just focus the input then leave immediately, the event is not fired.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**

**What is the expected behavior?**
I want that the `onBlur` event gets fired when clicking outside.

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Draft.js version: ^0.10.1
Chrome
Not sure

**Comment by mmmoussa** [comment] 2017-07-31 01:50
Hi @archieherbias, I am not able to reproduce this issue. Here's what I was testing with: https://jsfiddle.net/mmmoussa/9o2pms06/. Please provide more information if this is an issue you are able to reproduce.

**Comment by flarnie** [comment] 2017-08-04 22:37
Until we are able to reproduce the bug I'm going to close this, but please open a new issue if this comes up and you are able to get an example for reproducing it. Thanks!

**Closed by flarnie** 2017-08-04 22:37 UTC
Labels: needs-more-info

**Comment by kibaek-kimm** [comment] 2019-03-08 08:22
I have same issue. 
I think this issue show up when typing non-english. In my case is Korean.
When i typing in Korean, black line show up at the bottom of last character just like this.

![2019-03-08 5 17 50](https://user-images.githubusercontent.com/19887743/54016416-27e28f00-41c6-11e9-828c-34d7403a0617.png)

and then disappear last character which has the black line when blur events happen.
