### ISSUE TITLE
There are white spaces before and after a past content.

### ISSUE THREAD

**Issue by light564** [facebook/draft-js#1131] opened 2017-04-11 10:55 UTC
**Do you want to request a *feature* or report a *bug*?**
a bug
**What is the current behavior?**
There are 2 [draft editor](https://draftjs.org/)(draft home page), when you input some content in a editor, and copy(control + c) content, then past(control + v) this to another editor. There are white spaces before and after this content.
**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
in windows 7, chrome 56.0.2924.87

**Comment by hellendag** [comment] 2017-06-15 22:16
Can you provide a jsfiddle with a repro?

**Comment by flarnie** [comment] 2017-06-26 15:59
Thanks for reporting this - since we aren't able to reproduce it I'm closing, but if you are able to give more details please reopen or open a new issue.

**Closed by flarnie** 2017-06-26 15:59 UTC
Labels: needs-more-info
