### ISSUE TITLE
Add atomic block without prepending with empty line

### ISSUE THREAD

**Issue by bajalovic** [facebook/draft-js#850] opened 2016-12-07 17:52 UTC
For example, when editor is empty and I add image, I will get an empty line, then image (atomic block rendered) and then another empty line. Same thing happens on Facebook Notes editor. 

Is it possible to prevent draft from prepending with empty line? 

![image](https://cloud.githubusercontent.com/assets/1307779/20979659/0e99c800-bcae-11e6-9555-e7fca1803569.png)
And after adding an image there is an empty line before image.
![image](https://cloud.githubusercontent.com/assets/1307779/20979733/401be35e-bcae-11e6-9ffd-c74d0f98a601.png)

**Comment by zencephalon** [comment] 2016-12-26 07:39
I would appreciate this functionality as well.

**Comment by tobiasandersen** [comment] 2017-01-20 16:56
AtomicBlockUtils adds these empty blocks as a work around for https://github.com/facebook/draft-js/issues/203. You can add atomic blocks yourself, without any extra lines, but then you'd have to come up with a different solution to the problems mentioned in #203.

**Comment by agungsb** [comment] 2017-08-18 02:19
Hi @bajalovic , I've recently faced the same problem. But I managed to solve it. In case if you or someone else still haven't solved the problem, please refer to [this fiddle](https://jsfiddle.net/cczhL821/24/).

I hope it helps.

**Comment by niveditc** [comment] 2019-02-02 07:18
Closing since this is expected behavior & workarounds would cause other issues. More discussion on #327 as well.

**Closed by niveditc** 2019-02-02 07:18 UTC

**Comment by laneme** [comment] 2021-03-08 22:24
@agungsb buddy, can you get us a bit of explanation of what is going inside the inside function? I totally got lost after you initialized the `nextContentState` var. Thanks
