### ISSUE TITLE
Text input broken on android devices

### ISSUE THREAD

**Issue by ambewas** [facebook/draft-js#1443] opened 2017-10-19 08:16 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**
When typing text in a draftJS editor, for example on the homepage of draftjs.org, text disappears as soon as a user types a `space` or `enter`. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/stopachka/m6z0xn4r/.**
It is reproducible on the homepage of draftjs.org

**What is the expected behavior?**
Text should not disappear. 

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
Latest version of draft.js.

So far I've been able to reproduce this behavior on:
- Samsung devices running Android 6. 
- Google Nexus 5 running Android 6. 
- Google Pixel running Android 7.1.2.

The bug is not present on Samsung with android 5.1.1

**Comment by flarnie** [comment] 2017-10-19 14:53
Hi - thanks for reporting this, and sorry that I don't think we'll be able to fix it in the near future. Several folks, including myself, have done projects to improve mobile web support of Draft.js and because of the variation and inconsistency of mobile web browser keyboard/input events it's out of scope for us to fully support right now.

We have added a notice to the docs about the known issues - I believe this is a duplicate of https://github.com/facebook/draft-js/issues/1077, and there are several issues reporting similar observations if you look at issues tagged 'android' and/or 'ios' - https://github.com/facebook/draft-js/issues?q=is%3Aopen+is%3Aissue+label%3Aandroid

I hope that long term Facebook will find a solution for rich text on mobile web, but it's unclear whether that will be part of Draft.js or something else.

**Closed by flarnie** 2017-10-19 14:53 UTC

**Comment by iEchoic** [comment] 2018-02-15 18:09
@flarnie the Draft.js homepage is still giving the misleading impression that this is a cross-browser solution, which is causing many people to invest time into this library and then find unexpectedly that it doesn't work for them. Draft.js doesn't work on the most popular web browser in the world. Why is this still being marketed this way?

**Comment by stonecold123** [comment] 2018-02-22 13:30
@iEchoic 
The same problem also occurs with slate.js. 
Very frustrated.

**Comment by sandorvasas** [comment] 2019-02-04 10:41
One fcking year later, still not working. Bugfixes have been provided, but FB won't merge it.

**Comment by ducdev** [comment] 2019-05-19 17:39
Still not working...
