### ISSUE TITLE
Events are not being trigger when typing in a draft.js based component using automation

### ISSUE THREAD

**Issue by vasilesmartup** [facebook/draft-js#1506] opened 2017-11-13 13:25 UTC
I am currently typing some text in a draft.js based component, using the `type()` method from Cypress.io test automation framework. Text is being displayed in the component, but no events are being triggered, so the text is not being persisted in the Redux store. I tried triggering `manually` the events (`change`, `keypress`, etc), not working.

**Comment by juliankrispel** [comment] 2017-12-12 10:31
Hi @vasilesmartup I'm afraid I can't reproduce your problem.

The [onChange](https://draftjs.org/docs/api-reference-editor.html#onchange) event callback should be triggered when anything changes - it does for me so I'm closing this issue.

If you have a way to reproduce the issue lmk.

Also btw - please join the draft js community on slack for more immediate help: https://draftjs.herokuapp.com

**Closed by juliankrispel** 2017-12-12 10:31 UTC

**Comment by vicusbass** [comment] 2017-12-20 14:32
@juliankrispel Here's a demo https://www.youtube.com/watch?v=hdEglh3qdsY
As you can see, the first character typed is on the second row. In my particular case, our component has a character counter which is based on `onChange` event. Only the first character typed using Cypress.js automation tool is triggering the event, the rest of the characters are not doing anything. Here a demo test (I can give you a full project if you don't use Cypress)
```
describe('Smoke tests', function() {

  it.only('type stuff in draftJs control', function() {
    cy.visit('https://draftjs.org/')
    cy.get('[contenteditable="true"]').click().type('My first card is awesome')
  })
})

```

**Comment by juliankrispel** [comment] 2017-12-28 06:34
Hey @vicusbass thanks for reaching out again.

In your issue description you were saying that `onChange` isn't fired. In your demonstration however it clearly works, since if it wouldn't, the text wouldn't update at all.

It probably would help more to investigate with the cypress.js team tbh. This is basic functionality that is working in normal browsers, so it should also work using cypress...

On another note, this is still not enough to reproduce the issue. You're showing me a cypress script which doesn't actually reproduce the issue you're having - namely that `onChange` is not triggered.
