### ISSUE TITLE
Backspace and content editing broken on Pale Moon

### ISSUE THREAD

**Issue by wolfbeast** [facebook/draft-js#49] opened 2016-02-23 20:05 UTC
For a while now, content editing and especially backspacing over text (one has to press backspace one key at a time with pauses between presses) in the [Pale Moon browser](https://github.com/MoonchildProductions/Pale-Moon) has been broken. With the editor having been released as open source here now, we've finally been able to get more details about the apparent cause of the issue.

Holding down or rapidly pressing the key inserts control characters apparently instead of actually acting on the control characters as expected.

Reference post and thread:
https://forum.palemoon.org/viewtopic.php?f=29&t=6480&p=79607#p79607

The demo page has the same issue as the live Facebook production site, and displays the following behavior:

Upon loading first the following is thrown in the console:
````
[] "Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `BlockStyleControls`. See https://fb.me/react-warning-keys for more information."
[] "Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `InlineStyleControls`. See https://fb.me/react-warning-keys for more information."
````
With **every** keypress, another warning is spawned in the console:
````
[] "Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional."
````

**Comment by spicyj** [comment] 2016-02-23 20:10
Unfortunately those errors/warnings you list are actually expected for the moment and don't affect the behavior of the demo; you see the same warnings in any other browser. So that is a red herring. But hopefully the source is clean enough that it is possible to debug for someone who is motivated.

**Comment by wolfbeast** [comment] 2016-02-23 20:14
That's a real pity; I was hoping this would actually point at something specific that would allow for rapid pinpointing of the culprit. Is there a way to get more debugging info out of the demo page that could help?

**Comment by spicyj** [comment] 2016-02-23 20:15
No, nothing built-in.

**Comment by hellendag** [comment] 2016-02-23 21:39
Thanks for the report!

Is this function executing properly for each `keydown`? https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnKeyDown.js#L78

**Comment by wolfbeast** [comment] 2016-02-24 09:57
Who are you asking, @hellendag ?
At first glance I don't see anything wrong with the code in that function. Pale Moon supports KeyboardEvent.key (preferred) and KeyboardEvent.which (deprecated) which seems to be used here, and even KeyboardEvent.keyCode (also deprecated).

**Comment by wolfbeast** [comment] 2016-02-24 12:31
Question: are you relying on being sent a "keyup" event as well as a "keydown"? Because that may not happen if someone holds down the key (it's OS and browser dependent whether a "keyup" is sent for hold-repeat keys or not).

**Comment by spicyj** [comment] 2016-02-25 16:41
I don't think so, and that would be pretty unlikely anyway given that every other browser also sends many keydown events and only one keyup. Because Draft.js works well on all other browsers and Pale Moon is very rare, it is unlikely that anyone from Facebook will prioritize finding a fix for this (sorry!). But if this is important to you I encourage you to edit the code and figure out why the behavior is different. If there is a simple change we can make to improve compatibility I am sure we are likely to merge it. You might also find that it is an issue with Pale Moon's event handling that can be improved on the browser side.

**Comment by wolfbeast** [comment] 2016-02-25 18:41
If I look at event handling, then what I don't understand is why Firefox 26 would work (you say you've tested this), and Pale Moon would not -- it should not have any different behavior in that respect. If it relies on having the .repeat boolean flag (introduced in Firefox 28) then that would make some sense at least, but that wasn't available in v26 either.

What you are asking of me here is that I somehow completely audit this editor to somehow find out in code *I didn't write* where the code hangs up? Somehow reverse-engineer this and draw up process flow from code instead of the other way around? Aside from developing my browser?

As for the "rarity" of Pale Moon, that's debateable, but Facebook has been very clear about pointedly and expressly ignoring my requests at their address so far (including the form replies without follow-ups, lack of UA detection forcing us to fake Firefox or even Opera with varying success to have a usable site...). Doesn't exactly set a nice precedent for me to do your development work for you, now does it? But hey if you'd rather not have the half a million+ users we have to have a good experience, then please continue, by all means.
Sorry if I sound jaded.

I do need more to go on than "here have a blurb of js with no documentation and figure it out". So if you can at least point me in the right direction as to where to look... that might make a difference. I have a feeling it may actually be something really simple, but knowing where this simple change is needed (either in scripting or in the browser) is the crux.

**Comment by hellendag** [comment] 2016-02-25 19:12
Sorry it hasn't been a positive experience working with Facebook so far, it's understandable that that would be frustrating. Our UI/JS infra team is a pretty lean engineering org with a lot of ground to cover, so we do end up focusing on larger browser cohorts. That said, none of us wants to see anyone left behind, so I can try to lend a hand here.

One of my hopes from sharing this project is that we can move toward eliminating issues like these, since anyone can now investigate and play around with the code. I certainly don't mean for you to have to solve all problems for Pale Moon users, but I would hope that it is at least a better situation to have the code open than closed so that we can work together to find problem areas in the code. :)

In this case, given your repro steps, it seems like we can probably focus directly on keydown handling.

Backspace behavior is triggered by `keydown`. `keyup` is not currently observed by any Draft handlers. The repeat flag is not used.

Within `editOnKeyDown`, the key event is mapped to a command using the `keyBindingFn` prop, which by default is `getDefaultKeyBinding`. (https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnKeyDown.js#L79) The `which` value is used, as defined within React core (https://github.com/facebook/react/blob/dff05beeff9562647950461830ce42d484ca55fa/src/renderers/dom/client/syntheticEvents/SyntheticKeyboardEvent.js#L59). If this value corresponds to the backspace key, we determine the appropriate editor command based on modifier keys.

This command is then used to operate on the current `EditorState`, i.e. within https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/commands/keyCommandPlainBackspace.js. The resulting model change is then provided to the top-level component via the `onChange` prop function.

My hunch here is that something is going wrong in the key handling steps. When running an example, does the `which` value populate with the expected code while pressing/holding the backspace key?

**Comment by wolfbeast** [comment] 2016-02-25 19:24
I think I'm making some progress regardless. Thanks to @hellendag who pointed in the right direction with the keydown function and some trial-and-error on my end monitoring events. 

Something that is different in behavior in Pale Moon is that preventDefault() on keydown does **not** cancel the following keypress event. This is different than what Chrome or current Firefox (and I assume IE) does. I referenced to W3C spec to see what it says in case we are not spec compliant in Pale Moon:

> A default action MAY be cancelled through the invocation of the Event.preventDefault() method.

So the problem here is undefined (permitted either way) behavior in the spec that happens to have browser parity with "the big three". I gather this puts the event handler in draft.js in a confused state since the element will immediately be changed and a character will be inserted due to the keypress event which you want to prevent with preventDefault() in the case of command keys.

Unfortunately I wouldn't have a clue how to edit the draft.js code to take this into account, or even how to test this (and don't have the opportunity to familiarize myself with it); it builds on a specific framework I'm not familiar with.

Would this be something you can work with?

**Comment by hellendag** [comment] 2016-02-25 19:28
Nice, that sounds like our culprit.

Can you log to see if there is any output for the `data` value in https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnBeforeInput.js#L76? Since the event is falling through and Firefox fires keypress events even for control keys, we're probably making it to this point with some arbitrary character.

Within the `beforeInput` polyfill in the React core, we try to handle these Firefox control key keypresses, but we may be missing something here. https://github.com/facebook/react/blob/3b96650e39ddda5ba49245713ef16dbc52d25e9e/src/renderers/dom/client/eventPlugins/BeforeInputEventPlugin.js#L369

**Comment by wolfbeast** [comment] 2016-02-25 19:34
> Can you log to see if there is any output for the data value in https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnBeforeInput.js#L76?

I'm sorry but I have no clue how to set up an environment where I can check this. I'm not a web developer.

**Comment by wolfbeast** [comment] 2016-02-26 10:22
I've looked at the code in the browser and it should be feasible to change this behavior in Pale Moon for browser parity (and to satisfy our Facebook users) if it's a much more complex problem in the editor, but **I'd prefer to keep that as a last option** since it will impact web compatibility for other sites as well as extensions. I'm assuming we're not the only browser out there that takes this path for DOM key events, so having the js here handle it properly would be desirable, regardless.

**Comment by wolfbeast** [comment] 2016-02-27 18:38
Maybe I assumed wrong in general browser behavior. :smile:

I'll see if I can change our behavior, since reading more into it and having been able to pinpoint the cause here, it seems the more logical behavior to do what your editor expects.

**Comment by hellendag** [comment] 2016-02-28 00:19
@wolfbeast Haha, wish I could have. :) Thanks for your patience.

**Comment by wolfbeast** [comment] 2016-02-28 08:44
Just for the record, I can confirm that changing this behavior browser side (with a few hacks to test it) indeed solves this long-standing issue in draft-js when checking the demo page (and I assume on Facebook as well, haven't tested there yet). It does break part of our internal keystroke handling so this is going to take some time to address. If there is a solution or workaround in the meantime for people using Facebook that are currently having this issue, that would be greatly appreciated.

**Comment by hellendag** [comment] 2016-02-29 00:06
I can see if there's a good way to discard these keypresses within `BeforeInputEventPlugin` in the React core (https://github.com/facebook/react/blob/3b96650e39ddda5ba49245713ef16dbc52d25e9e/src/renderers/dom/client/eventPlugins/BeforeInputEventPlugin.js#L369).

What is the `which` value for the backspace keypress in Pale Moon?

**Comment by wolfbeast** [comment] 2016-02-29 08:01
the `which` value is (predictably) `8` for Backspace.

**Comment by hellendag** [comment] 2016-03-01 19:02
> Maybe it would be a good idea to discard all control keys. Most of them would have a value of 0 for which

Yeah, that was why I asked about <kbd>backspace</kbd>. Do you have a list of the control keys that will have non-`0` values on keypress? I'm happy to add them here.

**Comment by wolfbeast** [comment] 2016-03-03 10:53
Sorry for the delay here. I checked all most common control keys and combinations and it seems only backspace sends a non-`0` keypress event; the rest sends `0`

**Comment by DarkHorse16** [comment] 2016-03-03 12:39
Gerald Buffalo

**Comment by hellendag** [comment] 2016-03-09 20:43
@wolfbeast What do you think is the right approach here, in that case? Is there a reason that <kbd>backspace</kbd> should have a non-zero keypress event, or would it be okay to update it to match the other control keys?

**Comment by wolfbeast** [comment] 2016-03-10 13:25
"keypress" events have never been clearly defined, as far as I understood. Keypress events traditionally *should* fire on *all* actual key presses, including other control keys like Esc, but they don't. So there isn't exactly much rhyme or reason to it across browsers.
I haven't had time to look into internal key handling in our browser (Backspace is used for navigation, among other things, when not focusing input) and simply changing that to 0 may actually break things in the browser unless being very careful - it'll need time to research at the very least. There's probably a good reason why backspace has a non-0 event while other keys decide to give back 0. Reasoning may be browser parity, internal handling, or web compatibility compromises in the past -- I don't know the exact history of this code.

I think the right approach here would be for your script to treat keycode 8 as a control key (and probably a good idea to make this blanketing for all control/non-character keys) and not a character, which would improve compatibility with not just us, but likely other browsers as well that may send non-0 keypress codes for control characters.

**Comment by hellendag** [comment] 2016-03-10 19:22
> and probably a good idea to make this blanketing for all control/non-character keys

I'm hesitant to enumerate all possible non-character keycode values within the React core -- it's a [pretty long list](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key).

I think that if <kbd>backspace</kbd> is the problem right now, then let's go ahead and blacklist it. If we run across more keys that are causing this problem, we can come back to it. :)

**Comment by wolfbeast** [comment] 2016-03-10 22:30
keyboardevent.key is actually not the problem here unless you want to switch over from char codes to named keys.
What I was meaning to say is ignoring obvious non-character codes (< 0x20) in keypress events as control keys.

Either way, blacklisting backspace would certainly solve the current problem.

**Comment by DarkHorse16** [comment] 2016-03-14 22:27
https://play.google.com/store/apps/details?id=com.facebook.orca

Gerald Buffalo

**Comment by tylercraft** [comment] 2016-10-22 20:17
Closing as the referenced pull request comments that the problem is solved.

**Closed by tylercraft** 2016-10-22 20:17 UTC
Labels: bug, meta
