### ISSUE TITLE
Copy/Paste not preserving style on Safari

### ISSUE THREAD

**Issue by remko** [facebook/draft-js#147] opened 2016-03-03 16:02 UTC
When you copy paste a piece of text that has certain parts styled (e.g. bold), copy/paste does not preserve the style in Safari. I tried it with both the example on the Draft.js page and the FB Notes editor.

I was assuming this was a Safari limitation, but I've seen other rich-text editors (e.g. Google Docs, Medium) support copy/paste on Safari.

**Comment by hellendag** [comment] 2016-03-03 17:05
Thanks for the report! I am also able to reproduce this.

**Comment by hellendag** [comment] 2016-03-04 23:24
If anyone is interested in digging into copy/paste code and submitting a PR, that would be awesome. :) This would be a good starter task.

**Comment by Daniel15** [comment] 2016-03-06 06:16
Testing with various other WYSIWYG editors:
 - Works: [CKEditor](http://ckeditor.com/demo), [WYMEditor](http://wymeditor.github.io/wymeditor/dist/examples/01-basic.html), [Quill](http://quilljs.com), [NicEdit](http://nicedit.com/demos.php)
 - Doesn't work: [TinyMCE](https://www.tinymce.com/docs/demo/basic-example/)

Interestingly, copying from an editor that works (such as CKEditor) and pasting into Draft.js **does** retain the formatting, so I believe it's something happening on copy rather than on paste.

**Comment by Daniel15** [comment] 2016-03-06 06:22
This looks like CKEditor's implementation of copy/paste: https://github.com/ckeditor/ckeditor-dev/blob/3b32b2564d545c42a718bb43a9d3de9bd31ec0a0/plugins/clipboard/plugin.js

I'm not actively looking into this issue, just thought I'd do a very quick investigation for whoever wants to dig into it further :)

**Comment by remko** [comment] 2016-03-06 17:37
When copying from safari, the clipboard data doesn't seem to have any `text/html` data. Here are the types together with the `getData()` results:
```
type: com.apple.webarchive
type: application/x-webarchive
type: public.rtf
type: text/rtf
type: public.utf8-plain-text <SOME TEXT DATA>
type: text/plain <SOME TEXT DATA>
type: public.utf16-external-plain-text
type: CorePasteboardFlavorType 0x75743136
type: dyn.ah62d4rv4gk81n65yru
type: CorePasteboardFlavorType 0x7573746C
type: com.apple.traditional-mac-plain-text
type: CorePasteboardFlavorType 0x54455854
type: dyn.ah62d4rv4gk81g7d3ru
type: CorePasteboardFlavorType 0x7374796C
files: 0 files
items: undefined
```
Not sure how other editors handle this, but this might be something that needs fixing/enhancing in `fbjs` instead of in Draft.

**Comment by mitermayer** [comment] 2016-03-06 23:25
I will start working on a fix for this issue on a branch

**Comment by hellendag** [comment] 2016-03-07 01:50
Thanks @mitermayer!

**Comment by brookslyrette** [comment] 2016-03-30 16:16
Are you still working on this one @mitermayer? If not I'll give it a try.

**Comment by mitermayer** [comment] 2016-04-02 05:52
@brookslyrette Feel free to work on this one, got stuck on other PR's

**Comment by brookslyrette** [comment] 2016-04-08 02:01
Looks like this roots in a Safari issue: https://bugs.webkit.org/show_bug.cgi?id=19893

The data is in the OS but not accessible from the event in Safari. If you cut text with formatting in Safari the formatting will be preserved when pasted into Chrome. The opposite is also true.  I'm still digging into the issue, but the behaviour is odd to say the least. 

| From / To        |  Chrome           | Safari  |
| ------------- |:-------------:| -----:|
| Chrome      |  :white_check_mark:  | :white_check_mark: |
| Safari      | :white_check_mark:      |   :x: |

Is adding a 3rd party clipboard library a possibility?

**Comment by Daniel15** [comment] 2016-04-08 02:13
@brookslyrette How does CKEditor work around this issue? As per my comment
above, it handles copy/paste in Safari with no issues.

**Comment by brookslyrette** [comment] 2016-04-08 12:47
They work around the issue with an internal Clipboard for IE and Safari

During the paste event they check to see if the HTML data is trusted: `canClipboardApiBeTrusted`

https://github.com/ckeditor/ckeditor-dev/blob/12f0de314fd6fbee0bc4d35d541123d283fdecc9/plugins/clipboard/plugin.js#L1551

Then if it can't they use and internal `pastebin` via `getClipboardDataByPastebin`

https://github.com/ckeditor/ckeditor-dev/blob/12f0de314fd6fbee0bc4d35d541123d283fdecc9/plugins/clipboard/plugin.js#L1054

Paste bin seems to be a hidden DOM element with ID `cke_pastebin`

https://github.com/ckeditor/ckeditor-dev/blob/12f0de314fd6fbee0bc4d35d541123d283fdecc9/plugins/clipboard/plugin.js#L807

**Closed** 2016-06-15 19:04 UTC
Labels: bug, help wanted
