### ISSUE TITLE
can not insert a normal character  after the link

### ISSUE THREAD

**Issue by chengzhenping** [facebook/draft-js#1803] opened 2018-06-29 10:17 UTC
bug

insert a link first and can not insert a normal character  after the link

**Comment by niveditc** [comment] 2018-09-08 18:02
@chengzhenping - I cannot repro this. Please give more details for us to be able to help you here.

**Comment by skinandbones** [comment] 2018-09-11 19:08
@niveditc Perhaps this is referring to a problem editing an entity.  I am seeing the same issue.

Steps to reproduce:

1) open the link example: `examples/draft-0-10-0/link/link.html`
2) Add the text "This is a link."
3) Select "link" in the text
4) Click Add Link and enter any URL
5) Select elsewhere in the text to deselect.
6) Move the cursor to the end of "link" (between `k` and `.`)
7) Enter any character.  Ex, `s`.

Expected: the entire word "links" will be part of the entity (the entityRanges will change)
Actual: the characters of the link entity remains as "link"

<img width="650" alt="screen shot 2018-09-11 at 3 06 42 pm" src="https://user-images.githubusercontent.com/16830/45381791-56472f00-b5d4-11e8-9894-46e32f9e258a.png">
.

**Comment by thibaudcolas** [comment] 2018-09-11 19:16
@skinandbones I think this is the expected behavior. It got changed in the latest release, from the changelog:

> Fix issue where typing at the end of a link caused the link to continue. (Ian Jones in d16833b3)

See https://github.com/facebook/draft-js/issues/430#issuecomment-391657504 and the whole issue for more details.

**Comment by niveditc** [comment] 2018-09-15 18:52
Closing this issue since this is the expected behavior. We can discuss further on #430 if needed.

**Closed by niveditc** 2018-09-15 18:52 UTC
Labels: needs more info
