### ISSUE TITLE
convertFromRaw() function fails to convert raw datastructure with no blocks

### ISSUE THREAD

**Issue by smoak** [facebook/draft-js#2175] opened 2019-09-06 03:31 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

A TypeError is thrown: TypeError: contentState.getBlockMap(...).first(...) is undefined

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/gmertk/e61z7nfa/.**

Repro (you'll have to open your browser console to see the error): https://jsfiddle.net/wkxjL730/

**What is the expected behavior?**

No exception to be thrown

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

Version this breaks on: 0.11.0
Version this works on: unknown
Browsers this breaks on: Chrome, Firefox (I bet it's others but I do not have access to test them)

**Comment by thibaudcolas** [comment] 2019-09-07 22:28
This is a duplicate of #1660.

**Comment by shivavelingker** [comment] 2019-09-26 03:01
@thibaudcolas The referenced issue was reported over a year ago. Is there any update on its progress?

**Comment by thibaudcolas** [comment] 2019-09-26 20:16
@shivavelingker as far as I can see, no. But you should ask on that issue.

**Comment by ermanolca** [comment] 2020-01-13 13:25
any progress?

**Comment by mrkev** [comment] 2020-03-24 23:10
See #1660. This should be fixed.

**Closed by mrkev** 2020-03-24 23:10 UTC
