### ISSUE TITLE
An error in webpage about wrap text in editor

### ISSUE THREAD

**Issue by marti1125** [facebook/draft-js#191] opened 2016-03-10 22:16 UTC
have a look
![drafterrorwrap](https://cloud.githubusercontent.com/assets/223240/13686460/b9cfe49e-e6e3-11e5-8d16-4dcbc85d1597.png)

**Comment by marti1125** [comment] 2016-03-10 22:23
Firefox 45.0

**Comment by tasti** [comment] 2016-03-10 22:25
Confirmed this repros on Firefox 45.0 (OSX).

**Comment by tasti** [comment] 2016-03-10 22:29
Adding `word-wrap`/`word-break` to the `DraftEditor-content` fixes this.

Wanna send in a PR?

**Comment by hellendag** [comment] 2016-03-11 20:10
Fixed by https://github.com/facebook/draft-js/commit/7d575904b9a8e5cac762a17c5c6ef5689e915993. Thanks @alunyov!

**Closed by hellendag** 2016-03-11 20:10 UTC
Labels: bug

**Comment by PendletonJones** [comment] 2017-02-15 15:53
As a note to anyone who lands here debugging this problem, make sure that your Editor component is not inside a flexbox because that can cause this issue to occur even with the fix in 7d57590

**Comment by adavia** [comment] 2018-07-12 00:28
I am experiencing this same issue but only when using codeblocks
https://codesandbox.io/s/1oqr4xyy6j

**Comment by jacwright** [comment] 2021-08-11 15:08
Doesn't `word-break: break-all` break words in the middle, resulting in content like the following?

> This is a wonde
> rful example of
> fixing one prob
> lem only to cau
> se another.

I'm seeing this behavior in an app in the wild using Draft.js, and toggling off the word-break style in dev-tools makes it work as it should, but since nobody else has mentioned this problem in this issue or any other here, I'm not sure if it is a problem specific to that implementation. 🤔
