### ISSUE TITLE
handleBeforeInput is not trigger when input using an IME

### ISSUE THREAD

**Issue by kongkx** [facebook/draft-js#819] opened 2016-11-28 09:13 UTC
*feature*

`handleBeforeInput` is not triggered when using an IME. I wonder if it's possible to add some code to trigger something act like `handleBeforeInput` in `resolveComposition`.

**Comment by flarnie** [comment] 2017-10-24 23:08
Closing this as a duplicate of https://github.com/facebook/draft-js/issues/631

**Closed** 2017-10-24 23:08 UTC
Labels: duplicate
