### ISSUE TITLE
Image in quote

### ISSUE THREAD

**Issue by Nikcrysis** [facebook/draft-js#1080] opened 2017-03-16 18:11 UTC
Is there any way to insert entity like image in quoteblock?

**Comment by flarnie** [comment] 2017-06-15 22:06
Hi @Nikcrysis - can you explain more about your use case? I'm guessing that there isn't, but I'd like to hear more and see if we can figure something out.

**Comment by flarnie** [comment] 2017-06-26 15:56
I would need more info in order to help with this question - closing for now, since we use issues as a bug tracker and this isn't a reproducible bug.

**Closed by flarnie** 2017-06-26 15:56 UTC
Labels: needs-more-info
