### ISSUE TITLE
IOS native keyboard to input Chinese, lost focus

### ISSUE THREAD

**Issue by suyulin** [facebook/draft-js#544] opened 2016-07-18 06:36 UTC
IOS native keyboard to input Chinese, lost focus

**Comment by lan9** [comment] 2018-01-25 02:21
@suyulin I couldn't reproduce this issue on iOS 11. Since this issue has opened for more than 1 year -- could you try to reproduce again to see if it gets fixed by other patches?

**Closed** 2018-01-25 03:39 UTC
Labels: ios
