### ISSUE TITLE
could not run the *tex* example 

### ISSUE THREAD

**Issue by p2227** [facebook/draft-js#1408] opened 2017-09-26 10:49 UTC
**Do you want to request a *feature* or report a *bug*?**
report a *bug*

**What is the current behavior?**
could not run the *tex* example 

** If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started:  **
1. in dir `/Users/p2227/Program/git/react/` git clone this repo
2. npm i
3. cd examples/draft-0-10-0/tex
4. npm i
5. npm start
6. it report 

`Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/p2227/Program/git/react/draft-js/lib"
`

if i copy the dir `tex` to `/Users/p2227/Program/git/react/tex` ,it works!

**What is the expected behavior?**
it works, open localhost:3000 and run the example 

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
draft: 0.10.2
os:mac 10.12.6
node:v8.2.1

**Comment by flarnie** [comment] 2017-10-04 15:11
Thanks for reporting! I just noticed this recently too. Would love to have help fixing it, otherwise I will work on it when I have time.

Closing my own issue https://github.com/facebook/draft-js/issues/1413 as a duplicate of this.

**Comment by flarnie** [comment] 2017-10-25 23:20
This would be great to have fixed, sorry I still don't have bandwidth to look into it myself.

**Comment by guilhermecvm** [comment] 2017-11-11 11:11
Just did it

**Comment by againksy** [comment] 2018-02-05 03:26
So where it will be fixed?

**Comment by flarnie** [comment] 2018-02-08 01:29
Thanks for fixing this @guilhermecvm !

![happy_sloth](https://user-images.githubusercontent.com/1114467/35950666-7ed3a054-0c2c-11e8-82d1-77cb8549f476.jpg)

**Closed by flarnie** 2018-02-08 01:29 UTC
Labels: bug, documentation, help wanted
