### ISSUE TITLE
Bug definition in flow 0.51.1 - getTextContentFromFiles.js.flow - This type is incompatible with the expected param ...

### ISSUE THREAD

**Issue by szagi3891** [facebook/draft-js#1308] opened 2017-07-28 03:34 UTC
I using flow 0.51.1.

There is error when I run flow validation.

```
Error: node_modules/draft-js/lib/getTextContentFromFiles.js.flow:67
 67:     callback(reader.result);
                  ^^^^^^^^^^^^^ ArrayBuffer. This type is incompatible with the expected param type of
 46: function readFile(file: File, callback: (contents: string) => void): void {
                                                        ^^^^^^ string
```

**Comment by ckknight** [comment] 2017-08-02 16:55
Same with flow 0.49.1

**Comment by cedricmessiant** [comment] 2017-08-09 08:06
this is a duplicate of issue #1272 
(you can ignore the file in your `.flowconfig` until this is fixed)

**Comment by mitermayer** [comment] 2017-11-01 21:33
We are using `"flow-bin": "^0.53.1"` on the main repo and can no longer be able to reproduce this issue

**Closed by mitermayer** 2017-11-01 21:33 UTC
