### ISSUE TITLE
v0.11.2 input chinese after a single entity, this single entity will disappear, get the entityMap of null 

### ISSUE THREAD

**Issue by luqihao** [facebook/draft-js#2262] opened 2019-11-27 09:34 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. You can use this jsfiddle to get started: https://jsfiddle.net/gmertk/e61z7nfa/.**

**What is the expected behavior?**

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**

**Comment by mrkev** [comment] 2019-12-04 21:03
Sounds like it might be a duplicate of https://github.com/facebook/draft-js/issues/2082

**Closed by mrkev** 2019-12-04 21:03 UTC
