### ISSUE TITLE
Clear selection?

### ISSUE THREAD

**Issue by jisaacks** [facebook/draft-js#1020] opened 2017-02-22 22:16 UTC
When you have a selection of text, then click away blurring the component, then click back focusing the component again, the same selection remains. A second click must then be performed to clear the selection and place the cursor under the mouse.

This is bazaar and not the way textareas normally behave.

Normally when you blur a textarea, the selection is lost, and when you focus a textarea, the cursor is placed at the point in which you clicked.

I am trying recreate the normal textarea behavior and nothing I try seems to do the trick.

Since this only happens if there is a current selection. And it behaves correctly if there is no selection. My thought is to clear the selection on blur.

I have tried various combinations of using `moveSelectionToEnd`, and `forceSelection` and `acceptSelection` with `SelectionState.createEmpty` but nothing I try actually clears the selection. The previous selection is always there when I focus the component.

What is the appropriate way to clear the selection on blur and place the cursor at the correct spot on focus, the way a generic textarea behaves?

**Comment by elfey** [comment] 2017-03-27 18:50
If you've found the solution to this, that'd be great. This is extremely unintuitive and I'd love to disable this on my inputs... not even Facebook nor Instagram does this with their inputs.

**Comment by flarnie** [comment] 2017-06-15 22:30
I think we may have a fix for this. Looking into it with @spicyj right now.

**Comment by spicyj** [comment] 2017-06-15 22:51
This was originally done to work around a different bug in Chrome actually:

https://github.com/facebook/draft-js/blob/9414ad5c9c8e07fc565257653d2318c260e355f8/src/component/handlers/edit/editOnFocus.js#L35

I just noticed the bug seems fixed in Canary though! I ran the Chrome bisect script and found this:

```
You are probably looking for a change made after 467121 (known bad), but no later than 467132 (first known good).
CHANGELOG URL:
  https://chromium.googlesource.com/chromium/src/+log/fbf6b2dedcd7bd30dd82cdfd768ee5279d309721..45c1839662be78d913edb5c87bfaf9abc66bd9e5
```

In particular it looks like https://chromium.googlesource.com/chromium/src/+/feafc2de2c3e515247b5f45ab9ac9a4139b6cd46 is the likely fix and is in Chrome 60.0.3081.0 which is scheduled to hit stable channel in August. I think we can switch that back to acceptSelection if we no longer need to work around the bug.

**Comment by flarnie** [comment] 2017-06-15 23:28
We are testing the change internally now, will land a fix on Github once we verify that it doesn't cause any problems.

**Comment by reinvanimschoot** [comment] 2017-06-23 08:44
Is there any update on this? I've just encountered the same exact problem.

**Comment by flarnie** [comment] 2017-07-07 19:11
I have a commit on the way that will add the fix under a feature flag, and we can do a follow-up to enable it by default. It looks like no issues have come up in our testing.

**Comment by sanghin** [comment] 2017-07-20 07:28
Hi thanks for the fix, do you have any idea when this fix will be released ?

**Comment by flarnie** [comment] 2017-07-20 17:39
The fix is under a Feature Flag here on master:
https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnFocus.js#L37-L39
The comment there explains things.

We have been testing this internally, and need to decide if this is stable enough to make the default behavior.

I'll add it to the agenda for this week's Draft.js discussion. Thanks for checking in!

**Comment by flarnie** [comment] 2017-07-21 22:49
Another update - the fix seems to be stable in Chrome v60, and that should go out in a month or so. The release calendar is online here: https://www.chromium.org/developers/calendar

**Comment by flarnie** [comment] 2017-09-18 00:13
We have unflagged the fix internally and now on the master branch on Github, and so this will be fixed in the next release of Draft.js. See https://github.com/facebook/draft-js/commit/19b9b1c5007bcb3a4111ea31f8d9a8cda629a1ff

Thanks everyone for keeping this on the radar! :)

**Closed by flarnie** 2017-09-18 00:13 UTC

**Comment by Rohanhacker** [comment] 2019-05-29 15:11
getting the same issue with Chrome Version 74.0.3729.169 (Official Build) (64-bit).
Can be easily reproduced on facebook.com

**Comment by elio09** [comment] 2019-08-27 08:35
Hello, I have been working with this library for a few days and I have the same error, it is supposed to be fixed here, but I found that even on the official site this error persists, does anyone have any solution for this problem, thanks
![Captura de pantalla de 2019-08-27 10-34-03](https://user-images.githubusercontent.com/52199464/63755161-5d834d80-c8b6-11e9-8aaa-f34b8f1a3d63.png)

**Comment by chrisrobbins** [comment] 2021-03-26 14:30
I am still seeing this happen as well. Is there a way to programmatically clear the selection?
