### ISSUE TITLE
add "inlineStyleFn" so that I can add classes / attributes to inline styles

### ISSUE THREAD

**Issue by terencechow** [facebook/draft-js#1368] opened 2017-09-07 13:15 UTC
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**
Applying inline styles applies styles inline but I would like to have an inlineStyleFn that allows me to apply a class to the spans that are created. There exists a blockStyleFn that allows you to create classes on blocks but no similar functionality exists on inline styles. 

Currently there are issues [here](https://www.google.co.uk/search?q=multiple+entities+per+character&oq=multiple+entities+per+character&aqs=chrome..69i57.5975j0j4&sourceid=chrome&ie=UTF-8) and [here](https://github.com/facebook/draft-js/issues/246) with not being able to create multiple entities on the same character. This makes it impossible to do Comments + Links on the same characters without resorting to hacks. However an `inlineStyleFn` would largely solve this since we could add classes or data-attributes to our inline styles and potentially have some sort of decorator that regexes based on class / data-attributes. 

**What is the expected behavior?**
be able to add classes to inline styles

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
current version is 0.10.1 but all versions and OS' are affected

**Comment by thibaudcolas** [comment] 2018-02-04 11:35
I believe this is a duplicate of #957, which is `wontfix`.

**Comment by flarnie** [comment] 2018-02-07 16:17
Yup - thanks @thibaudcolas

**Closed by flarnie** 2018-02-07 16:17 UTC
