### ISSUE TITLE
Editor examples stripping out newlines in a copy-pasted text

### ISSUE THREAD

**Issue by kaushik94** [facebook/draft-js#757] opened 2016-11-01 11:29 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I copy paste this text 
```
I’m not sure that the DAWN op-ed: Three questions from Pakistan that India needs to answer is a sincere one. For DAWN’s standards, it was of pretty poor quality.

First, the author asks how India can be corrupt if it is also democratic. The assumption is that democracy is a magic wand that removes all illnesses. For its size and poverty, India ranks fairly well in the Corruption Perceptions Index. 100 nations [including China and Pakistan] rank behind India. Of the poorer countries, only 4 [Bhutan, Senegal, Lesotho, Rwanda] rank ahead of India and all of them are very small. India is corrupt, but most of the world is far more corrupt.

Second, the author wonders how India can have religious violence when it is secular. Again, the assumption is that having a secular Constitution would magically bring about all the necessary security infrastructure such as a modern police force to contain riots. For the size of its population, India’s religious violence rate is quite low. And way lower than Pakistan. The status of Muslims in India is infinitely better than that of Hindus in Pakistan.

Third, the author asks how the people can love their army in a democratic setup. I guess the author knows nothing of US. Democracy doesn’t mean you hate the military. In fact, being in a dangerous neighborhood with a key terrorism sponsor next to us, Indians are quite thankful that their army contains most of the bad stuff trying to get past our borders.

All in all, a very poor article. India has its share of problems and is poor, given the circumstances of the past few hundred years. However, when it is compared to its non-democratic neighbors, India fares way better. While Indians might whine a lot about their politics, I don’t know of any who would trade their system for the one run in Pakistan or Myanmar.
```
into the `rich.html` example of the current stable(0.9.1)
The output turns out to be
```
I’m not sure that the DAWN op-ed: Three questions from Pakistan that India needs to answer is a sincere one. For DAWN’s standards, it was of pretty poor quality.First, the author asks how India can be corrupt if it is also democratic. The assumption is that democracy is a magic wand that removes all illnesses. For its size and poverty, India ranks fairly well in the Corruption Perceptions Index. 100 nations [including China and Pakistan] rank behind India. Of the poorer countries, only 4 [Bhutan, Senegal, Lesotho, Rwanda] rank ahead of India and all of them are very small. India is corrupt, but most of the world is far more corrupt.Second, the author wonders how India can have religious violence when it is secular. Again, the assumption is that having a secular Constitution would magically bring about all the necessary security infrastructure such as a modern police force to contain riots. For the size of its population, India’s religious violence rate is quite low. And way lower than Pakistan. The status of Muslims in India is infinitely better than that of Hindus in Pakistan.Third, the author asks how the people can love their army in a democratic setup. I guess the author knows nothing of US. Democracy doesn’t mean you hate the military. In fact, being in a dangerous neighborhood with a key terrorism sponsor next to us, Indians are quite thankful that their army contains most of the bad stuff trying to get past our borders.All in all, a very poor article. India has its share of problems and is poor, given the circumstances of the past few hundred years. However, when it is compared to its non-democratic neighbors, India fares way better. While Indians might whine a lot about their politics, I don’t know of any who would trade their system for the one run in Pakistan or Myanmar.
```

**What is the expected behavior?**
It should preserve the newlines, can someone confirm me if this is the same with others as well. Am I missing something?

**Which versions of Draft.js, and which browser / OS are affected by this issue? Did this work in previous versions of Draft.js?**
0.9.1
Chrome

**Comment by davidchang** [comment] 2016-11-01 18:03
Thank you for reporting @kaushik94 - this is certainly a bug and looks to be a dupe of this issue: https://github.com/facebook/draft-js/issues/523#issuecomment-250174242

I'm going to close this in favor of that and may create a master task to consolidate related tasks.

**Closed by davidchang** 2016-11-01 18:03 UTC
