### ISSUE TITLE
`Invalid calling object` in IE11 and Edge

### ISSUE THREAD

**Issue by diiq** [facebook/draft-js#1230] opened 2017-05-30 19:02 UTC
Entering a character causes an `Invalid calling object` error in IE and Edge.

Using draftjs v 0.10.1 on IE 11 and Edge, when entering a character,  I get an `Invalid calling object` error at the following line:
https://github.com/facebook/draft-js/blob/6f2bf66bacff3ffac234fc21ff3720344ff92776/src/component/handlers/edit/editOnBeforeInput.js#L175

If I bind `setImmediate` to `window` alongside my other polyfills, the problem goes away.

```
window.setImmediate = window.setImmediate.bind(window);
```

Which implies that somewhere setImmediate is being orphaned from window. 

I suspect this is happening due to a bad interaction of multiple libraries attempting to polyfill setImmediate, and IE not needing a polyfill at all -- but I cannot point directly to the culprits. 

Leaving this here more for future searchers than because I believe there's much for draft-js to actually fix? So feel free to close if this accumulates no "me too!"s

**Comment by flarnie** [comment] 2017-06-15 21:13
Thanks for reporting this @diiq - I haven't seen this issue come up in our uses of Draft.js but if you or anyone is able to isolate which polyfills are causing this we can add it to our documentation and file an issue with them. For now closing this since I'm not sure there is anything actionable we can do.

**Closed by flarnie** 2017-06-15 21:13 UTC

**Comment by slorber** [comment] 2017-10-02 17:58
I can confirm I see this error in 0.10.1 on IE11 and when editor is blurred it seems last character is erased

0.10.3 seems to fix the problem
